Destroy: delete user before deleting files
Otherwise this error happens in macOS:

```
Removing /Users/pi...
Enter sudo password (required to destroy installation):
Error: Error: sudo command 'rm -rf /Users/pi' failed (exit code 1): rm: /Users/pi/Pictures: Operation not permitted
rm: /Users/pi/Library/Application Support: Operation not permitted
rm: /Users/pi/Library/Preferences: Operation not permitted
rm: /Users/pi/Library/Mail: Operation not permitted
rm: /Users/pi/Library/Containers/com.apple.ImageIO.imageimporter/.com.apple.containermanagerd.metadata.plist: Operation not permitted
rm: /Users/pi/Library/Containers/com.apple.ImageIO.imageimporter: Operation not permitted
rm: /Users/pi/Library/Containers/com.apple.PDFKit.PDFImporter/.com.apple.containermanagerd.metadata.plist: Operation not permitted
rm: /Users/pi/Library/Containers/com.apple.PDFKit.PDFImporter: Operation not permitted
rm: /Users/pi/Library/Containers: Operation not permitted
rm: /Users/pi/Library/ContainerManager: Operation not permitted
rm: /Users/pi/Library/Caches/com.apple.containermanagerd: Operation not permitted
rm: /Users/pi/Library/Caches: Operation not permitted
rm: /Users/pi/Library: Operation not permitted
rm: /Users/pi: Operation not permitted
    at ChildProcess.<anonymous> (/Users/pi/Work/skynot/dist/index.js:149:24)
    at ChildProcess.emit (node:events:509:20)
    at maybeClose (node:internal/child_process:1108:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

```